### ISSUE TITLE
Error on P2P on 2 RTX 5090: mapping of buffer object failed or code=205(cudaErrorMapBufferObjectFailed) "cudaDeviceEnablePeerAccess(gpuid[1], 0)

### ISSUE THREAD

**Issue by Panchovix** [tinygrad/open-gpu-kernel-modules#44]
### NVIDIA Open GPU Kernel Modules Version

570.133, 570.144, 570.148, 570.153

### Operating System and Version

Fedora 41

### Hardware

RTX 5090x2+RTX4090x2+RTX3090x2+A6000

AMD Ryzen 7 7800X3D

192GB RAM

MSI Carbon X670E

### Kernel Release

6.14.9

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [ ] I am running on a stable kernel release.

### Build Command

-

### Terminal output/Build Log

-

### More Info

Hi there. I'm trying to use P2P on two RTX 5090, but I get the next issues:

```
pancho@fedora:~/cuda-samples/build/Samples/5_Domain_Specific/p2pBandwidthLatencyTest$ export CUDA_VISIBLE_DEVICES=2,3
pancho@fedora:~/cuda-samples/build/Samples/5_Domain_Specific/p2pBandwidthLatencyTest$ ./p2pBandwidthLatencyTest 
[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, NVIDIA GeForce RTX 5090, pciBusID: 1, pciDeviceID: 0, pciDomainID:0
Device: 1, NVIDIA GeForce RTX 5090, pciBusID: 3, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Access Peer Device=1
Device=1 CAN Access Peer Device=0

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) and unstable Latency (us) in those cases.

P2P Connectivity Matrix
     D\D     0     1
     0       1     1
     1       1     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1 
     0 1728.49  24.63 
     1  24.70 1761.56 
Unidirectional P2P=Enabled Bandwidth (P2P Writes) Matrix (GB/s)
Cuda failure /home/pancho/cuda-samples/Samples/5_Domain_Specific/p2pBandwidthLatencyTest/p2pBandwidthLatencyTest.cu:192: 'mapping of buffer object failed'
pancho@fedora:~/cuda-samples/build/Samples/0_Introduction/simpleP2P$ ./simpleP2P 
[./simpleP2P] - Starting...
Checking for multiple GPUs...
CUDA-capable device count: 2

Checking GPU(s) for support of peer to peer memory access...
> Peer access from NVIDIA GeForce RTX 5090 (GPU0) -> NVIDIA GeForce RTX 5090 (GPU1) : Yes
> Peer access from NVIDIA GeForce RTX 5090 (GPU1) -> NVIDIA GeForce RTX 5090 (GPU0) : Yes
Enabling peer access between GPU0 and GPU1...
CUDA error at /home/pancho/cuda-samples/Samples/0_Introduction/simpleP2P/simpleP2P.cu:130 code=205(cudaErrorMapBufferObjectFailed) "cudaDeviceEnablePeerAccess(gpuid[1], 0)" 
```

I have other GPUs on my system (A6000, 3090s, 4090s) and P2P works fine on these cards.

I did try with the patch mentioned here https://github.com/tinygrad/open-gpu-kernel-modules/issues/29#issuecomment-2765260985, but as I mentioned on https://github.com/tinygrad/open-gpu-kernel-modules/issues/29#issuecomment-2972995631, it doesn't seem to work. I edited the files mentioned but there was no difference.

I have also tried https://github.com/tinygrad/open-gpu-kernel-modules/tree/570.148.08-p2p branch, but issue is still there.

I installed the driver -> then the patch with ./install.sh.

IOMMU and PCIe ACS are disabled.

Any help is appreciated.

**Comment by Panchovix** [comment]
A more complete log with the others GPUs alone and in the mix

```
pancho@fedora:~/cuda-samples/build/Samples/5_Domain_Specific/p2pBandwidthLatencyTest$ export CUDA_VISIBLE_DEVICES=0,1
pancho@fedora:~/cuda-samples/build/Samples/5_Domain_Specific/p2pBandwidthLatencyTest$ ./p2pBandwidthLatencyTest 
[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, NVIDIA GeForce RTX 4090, pciBusID: 2, pciDeviceID: 0, pciDomainID:0
Device: 1, NVIDIA GeForce RTX 4090, pciBusID: 17, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Access Peer Device=1
Device=1 CAN Access Peer Device=0

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) and unstable Latency (us) in those cases.

P2P Connectivity Matrix
     D\D     0     1
     0       1     1
     1       1     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1 
     0 1008.06   6.34 
     1   6.34 926.75 
Unidirectional P2P=Enabled Bandwidth (P2P Writes) Matrix (GB/s)
   D\D     0      1 
     0 1015.27   6.60 
     1   6.60 945.63 
Bidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1 
     0 1018.92   8.66 
     1   8.67 926.39 
Bidirectional P2P=Enabled Bandwidth Matrix (GB/s)
   D\D     0      1 
     0 1016.92  12.88 
     1  12.88 924.56 
P2P=Disabled Latency Matrix (us)
   GPU     0      1 
     0   1.37  10.28 
     1  10.33   1.29 

   CPU     0      1 
     0   1.61   4.89 
     1   5.01   1.60 
P2P=Enabled Latency (P2P Writes) Matrix (us)
   GPU     0      1 
     0   1.36   0.88 
     1   0.90   1.28 

   CPU     0      1 
     0   1.61   1.35 
     1   1.35   1.58 

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
pancho@fedora:~/cuda-samples/build/Samples/5_Domain_Specific/p2pBandwidthLatencyTest$ export CUDA_VISIBLE_DEVICES=4,5,6
pancho@fedora:~/cuda-samples/build/Samples/5_Domain_Specific/p2pBandwidthLatencyTest$ ./p2pBandwidthLatencyTest 
[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, NVIDIA RTX A6000, pciBusID: 12, pciDeviceID: 0, pciDomainID:0
Device: 1, NVIDIA GeForce RTX 3090, pciBusID: 6, pciDeviceID: 0, pciDomainID:0
Device: 2, NVIDIA GeForce RTX 3090, pciBusID: d, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Access Peer Device=1
Device=0 CAN Access Peer Device=2
Device=1 CAN Access Peer Device=0
Device=1 CAN Access Peer Device=2
Device=2 CAN Access Peer Device=0
Device=2 CAN Access Peer Device=1

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) and unstable Latency (us) in those cases.

P2P Connectivity Matrix
     D\D     0     1     2
     0       1     1     1
     1       1     1     1
     2       1     1     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2 
     0 583.89   3.07   3.06 
     1   3.09 944.11   3.08 
     2   3.06   3.07 917.50 
Unidirectional P2P=Enabled Bandwidth (P2P Writes) Matrix (GB/s)
   D\D     0      1      2 
     0 584.77   2.32   6.60 
     1   2.08 946.97   2.08 
     2   6.60   2.32 918.58 
Bidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2 
     0 588.29   3.23   3.18 
     1   3.23 953.03   3.24 
     2   3.17   3.24 924.28 
Bidirectional P2P=Enabled Bandwidth Matrix (GB/s)
   D\D     0      1      2 
     0 588.40   2.32   6.60 
     1   2.31 950.43   2.32 
     2   6.60   2.32 923.46 
P2P=Disabled Latency Matrix (us)
   GPU     0      1      2 
     0   1.89  19.50  24.48 
     1  19.39   1.61  19.34 
     2  24.44  19.56   1.67 

   CPU     0      1      2 
     0   1.67   5.16   4.99 
     1   4.83   1.70   4.73 
     2   4.79   6.08   1.61 
P2P=Enabled Latency (P2P Writes) Matrix (us)
   GPU     0      1      2 
     0   1.91   1.86   1.92 
     1   1.44   1.64   1.40 
     2   1.78   1.75   1.57 

   CPU     0      1      2 
     0   1.60   1.30   1.35 
     1   1.34   1.57   1.38 
     2   1.37   1.30   1.60 

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
pancho@fedora:~/cuda-samples/build/Samples/5_Domain_Specific/p2pBandwidthLatencyTest$ export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6
pancho@fedora:~/cuda-samples/build/Samples/5_Domain_Specific/p2pBandwidthLatencyTest$ ./p2pBandwidthLatencyTest 
[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, NVIDIA GeForce RTX 4090, pciBusID: 2, pciDeviceID: 0, pciDomainID:0
Device: 1, NVIDIA GeForce RTX 4090, pciBusID: 17, pciDeviceID: 0, pciDomainID:0
Device: 2, NVIDIA GeForce RTX 5090, pciBusID: 1, pciDeviceID: 0, pciDomainID:0
Device: 3, NVIDIA GeForce RTX 5090, pciBusID: 3, pciDeviceID: 0, pciDomainID:0
Device: 4, NVIDIA RTX A6000, pciBusID: 12, pciDeviceID: 0, pciDomainID:0
Device: 5, NVIDIA GeForce RTX 3090, pciBusID: 6, pciDeviceID: 0, pciDomainID:0
Device: 6, NVIDIA GeForce RTX 3090, pciBusID: d, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Access Peer Device=1
Device=0 CANNOT Access Peer Device=2
Device=0 CANNOT Access Peer Device=3
Device=0 CANNOT Access Peer Device=4
Device=0 CANNOT Access Peer Device=5
Device=0 CANNOT Access Peer Device=6
Device=1 CAN Access Peer Device=0
Device=1 CANNOT Access Peer Device=2
Device=1 CANNOT Access Peer Device=3
Device=1 CANNOT Access Peer Device=4
Device=1 CANNOT Access Peer Device=5
Device=1 CANNOT Access Peer Device=6
Device=2 CANNOT Access Peer Device=0
Device=2 CANNOT Access Peer Device=1
Device=2 CAN Access Peer Device=3
Device=2 CANNOT Access Peer Device=4
Device=2 CANNOT Access Peer Device=5
Device=2 CANNOT Access Peer Device=6
Device=3 CANNOT Access Peer Device=0
Device=3 CANNOT Access Peer Device=1
Device=3 CAN Access Peer Device=2
Device=3 CANNOT Access Peer Device=4
Device=3 CANNOT Access Peer Device=5
Device=3 CANNOT Access Peer Device=6
Device=4 CANNOT Access Peer Device=0
Device=4 CANNOT Access Peer Device=1
Device=4 CANNOT Access Peer Device=2
Device=4 CANNOT Access Peer Device=3
Device=4 CAN Access Peer Device=5
Device=4 CAN Access Peer Device=6
Device=5 CANNOT Access Peer Device=0
Device=5 CANNOT Access Peer Device=1
Device=5 CANNOT Access Peer Device=2
Device=5 CANNOT Access Peer Device=3
Device=5 CAN Access Peer Device=4
Device=5 CAN Access Peer Device=6
Device=6 CANNOT Access Peer Device=0
Device=6 CANNOT Access Peer Device=1
Device=6 CANNOT Access Peer Device=2
Device=6 CANNOT Access Peer Device=3
Device=6 CAN Access Peer Device=4
Device=6 CAN Access Peer Device=5

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) and unstable Latency (us) in those cases.

P2P Connectivity Matrix
     D\D     0     1     2     3     4     5     6
     0       1     1     0     0     0     0     0
     1       1     1     0     0     0     0     0
     2       0     0     1     1     0     0     0
     3       0     0     1     1     0     0     0
     4       0     0     0     0     1     1     1
     5       0     0     0     0     1     1     1
     6       0     0     0     0     1     1     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2      3      4      5      6 
     0 1008.06   6.34   6.53   6.53   6.07   3.11   3.09 
     1   6.33 927.85   6.53   6.53   6.07   3.11   3.09 
     2   6.64   6.64 1749.78  24.69   6.23   4.92   4.90 
     3   6.64   6.64  24.75 1759.57   6.23   4.94   4.90 
     4   6.37   6.37   6.45   6.45 585.43   3.07   3.06 
     5   3.21   3.21   5.06   5.05   3.09 945.82   3.09 
     6   3.20   3.06   5.06   5.08   3.06   3.07 916.96 
Unidirectional P2P=Enabled Bandwidth (P2P Writes) Matrix (GB/s)
Cuda failure /home/pancho/cuda-samples/Samples/5_Domain_Specific/p2pBandwidthLatencyTest/p2pBandwidthLatencyTest.cu:192: 'mapping of buffer object failed'
```

```
pancho@fedora:~/cuda-samples/build/Samples/0_Introduction/simpleP2P$ export CUDA_VISIBLE_DEVICES=0,1
pancho@fedora:~/cuda-samples/build/Samples/0_Introduction/simpleP2P$ ./simpleP2P 
[./simpleP2P] - Starting...
Checking for multiple GPUs...
CUDA-capable device count: 2

Checking GPU(s) for support of peer to peer memory access...
> Peer access from NVIDIA GeForce RTX 4090 (GPU0) -> NVIDIA GeForce RTX 4090 (GPU1) : Yes
> Peer access from NVIDIA GeForce RTX 4090 (GPU1) -> NVIDIA GeForce RTX 4090 (GPU0) : Yes
Enabling peer access between GPU0 and GPU1...
Allocating buffers (64MB on GPU0, GPU1 and CPU Host)...
Creating event handles...
cudaMemcpyPeer / cudaMemcpy between GPU0 and GPU1: 6.13GB/s
Preparing host buffer and memcpy to GPU0...
Run kernel on GPU1, taking source data from GPU0 and writing to GPU1...
Run kernel on GPU0, taking source data from GPU1 and writing to GPU0...
Copy data back to host from GPU0 and verify results...
Disabling peer access...
Shutting down...
Test passed
pancho@fedora:~/cuda-samples/build/Samples/0_Introduction/simpleP2P$ export CUDA_VISIBLE_DEVICES=2,3
pancho@fedora:~/cuda-samples/build/Samples/0_Introduction/simpleP2P$ ./simpleP2P 
[./simpleP2P] - Starting...
Checking for multiple GPUs...
CUDA-capable device count: 2

Checking GPU(s) for support of peer to peer memory access...
> Peer access from NVIDIA GeForce RTX 5090 (GPU0) -> NVIDIA GeForce RTX 5090 (GPU1) : Yes
> Peer access from NVIDIA GeForce RTX 5090 (GPU1) -> NVIDIA GeForce RTX 5090 (GPU0) : Yes
Enabling peer access between GPU0 and GPU1...
CUDA error at /home/pancho/cuda-samples/Samples/0_Introduction/simpleP2P/simpleP2P.cu:130 code=205(cudaErrorMapBufferObjectFailed) "cudaDeviceEnablePeerAccess(gpuid[1], 0)" 
```

**Comment by changzhi1990** [comment]
I also met this problem.

**Comment by ChiikawaSama** [comment]
+1

**Comment by changzhi1990** [comment]
Please refer to https://github.com/tinygrad/open-gpu-kernel-modules/issues/33#issuecomment-3056266683. It can resolve my issue.

**Comment by ChiikawaSama** [comment]
> #33 (comment)

thanks for your help, but my 5090s' bar size is already 32GB, still cannot resolve this problem. May you tell me what branch do you use to hack p2p?

**Comment by changzhi1990** [comment]
> > [#33](https://github.com/tinygrad/open-gpu-kernel-modules/issues/33) (comment)
> 
> thanks for your help, but my 5090s' bar size is already 32GB, still cannot resolve this problem. May you tell me what branch do you use to hack p2p?

https://github.com/tinygrad/open-gpu-kernel-modules/tree/570.124.06-p2p

**Comment by ChiikawaSama** [comment]
> > > [#33](https://github.com/tinygrad/open-gpu-kernel-modules/issues/33) (comment)
> > 
> > 
> > thanks for your help, but my 5090s' bar size is already 32GB, still cannot resolve this problem. May you tell me what branch do you use to hack p2p?
> 
> https://github.com/tinygrad/open-gpu-kernel-modules/tree/570.124.06-p2p

thanks a lot! i'll try

**Comment by ChiikawaSama** [comment]
> > > [#33](https://github.com/tinygrad/open-gpu-kernel-modules/issues/33) (comment)
> > 
> > 
> > thanks for your help, but my 5090s' bar size is already 32GB, still cannot resolve this problem. May you tell me what branch do you use to hack p2p?
> 
> https://github.com/tinygrad/open-gpu-kernel-modules/tree/570.124.06-p2p

still not running, sad😂

**Comment by JzhJay** [comment]
Do you have any progress on this issue? I've been getting stuck at the same place...

**Comment by Panchovix** [comment]
No luck yet, still same issue sadly. Latest branch was also updated like 1 month ago so not much hopes for now :(.

**Comment by JzhJay** [comment]
> No luck yet, still same issue sadly. Latest branch was also updated like 1 month ago so not much hopes for now :(.

@Panchovix Yea I'm also trying with the latest branch. I'm wondering what's your BIOS settings like? Have you also disabled IOMMU and enable resize BAR?

**Comment by Panchovix** [comment]
Yes, basically disabled PCIe ACS and IOMMU, but no luck with the 5090s, but it does work fine with some 4090s and 3090s I have on my PC. Probably it is something related to the code itself that doesn't support the 5090 for now.

**Comment by JzhJay** [comment]
> Yes, basically disabled PCIe ACS and IOMMU, but no luck with the 5090s, but it does work fine with some 4090s and 3090s I have on my PC. Probably it is something related to the code itself that doesn't support the 5090 for now.

Yes, I guess there is some slight difference about the buffer manipulation between 4090 and 5090, I'm trying to figure it out

**Comment by Panchovix** [comment]
At least I tried what was mentioned on https://github.com/tinygrad/open-gpu-kernel-modules/issues/29#issuecomment-2765260985 but no luck. I'm not sure when doing the changes are actually applied when building.

Maybe it works on Ubuntu or something? But with Fedora, no luck.

**Comment by aluo-x** [comment]
The fork here: https://github.com/aikitoria/open-gpu-kernel-modules/ should have support for 5090

**Comment by Panchovix** [comment]
> The fork here: https://github.com/aikitoria/open-gpu-kernel-modules/ should have support for 5090

Will try with it on the weekend, but has someone tested and got it working?

**Comment by Panchovix** [comment]
@aluo-x I can confirm that fork works with the 5090 and P2P. Thanks!

Thanks @aikitoria for your work. 

```
pancho@fedora:~/cuda-samples/build/Samples/5_Domain_Specific/p2pBandwidthLatencyTest$ ./p2pBandwidthLatencyTest 
[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, NVIDIA GeForce RTX 5090, pciBusID: 1, pciDeviceID: 0, pciDomainID:0
Device: 1, NVIDIA GeForce RTX 5090, pciBusID: 3, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Access Peer Device=1
Device=1 CAN Access Peer Device=0

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) and unstable Latency (us) in those cases.

P2P Connectivity Matrix
     D\D     0     1
     0       1     1
     1       1     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1 
     0 1736.17  24.35 
     1  24.62 1771.60 
Unidirectional P2P=Enabled Bandwidth (P2P Writes) Matrix (GB/s)
   D\D     0      1 
     0 1741.98  28.38 
     1  28.67 1755.68 
Bidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1 
     0 1737.98  30.20 
     1  30.47 1769.44 
Bidirectional P2P=Enabled Bandwidth Matrix (GB/s)
   D\D     0      1 
     0 1751.59  52.19 
     1  55.94 1765.44 
P2P=Disabled Latency Matrix (us)
   GPU     0      1 
     0   2.08  14.38 
     1  14.65   2.10 

   CPU     0      1 
     0   1.75   4.67 
     1   4.66   1.63 
P2P=Enabled Latency (P2P Writes) Matrix (us)
   GPU     0      1 
     0   2.08   0.48 
     1   0.48   2.07 

   CPU     0      1 
     0   1.68   1.27 
     1   1.29   1.68 
```

**Comment by josephgimenez** [comment]
Got dual RTX 5090s on AM5 (Ryzen 9 9950X3D) doing P2P. There's a third gate beyond the patches in this thread — sharing in case it helps others.

**Setup**: 2× RTX 5090, ASUS X870E-class board, AMD-Vi disabled in BIOS (no ACS toggle exposed but turned out unnecessary), `nvidia-driver-595-open` (595.58.03), patched from source.

**What's already in this thread** (chipset bypass + huanzhang12's aperture fix) gets the P2P matrix from `CNS` → `OK` and `cudaDeviceCanAccessPeer` returns 1 — but `cudaDeviceEnablePeerAccess` still fails with `cudaErrorMapBufferObjectFailed` (error 205). Same as @Panchovix in #44.

**The missing piece**: dmesg revealed an assertion in `_kbusCreateStaticBar1IOMMUMapping`:

```
NVRM: The peer DMA address 0x1800400000 is not aligned at 0x20000000
NVRM: IOMMU mapping failed from GPU1 to GPU0
kern_bus_gh100.c:1639
```

Consumer Blackwell's static BAR1 region starts at `BAR1_base + 0x400000` (4 MB offset, presumably for console fb / scratch). The driver requires 512 MB alignment for peer DMA mappings, which the 4 MB offset violates. On EPYC server boards the layout apparently aligns naturally; on AM5 it doesn't.

---

## The complete recipe to enable P2P on Blackwell consumer (595.58.03)

**1. BIOS**

- Disable IOMMU / AMD-Vi
- ACS toggle (if exposed) — wasn't required on my AM5 board

**2. Source patches** against `NVIDIA/open-gpu-kernel-modules` at tag `595.58.03`

(a) huanzhang12's aperture redirect — `src/nvidia/inc/libraries/mmu/gmmu_fmt.h`, the `gmmuFieldSetAperture` inline function:

```diff
-    nvFieldSetEnum(&pAperture->_enum, value, pMem);
+    GMMU_APERTURE new_value;
+    if (value == GMMU_APERTURE_PEER) {
+        new_value = GMMU_APERTURE_SYS_NONCOH;
+    } else {
+        new_value = value;
+    }
+    nvFieldSetEnum(&pAperture->_enum, new_value, pMem);
```

(b) huanzhang12's WC-disable — `kernel-open/common/inc/nv-linux.h`, in `nv_ioremap_wc`:

```diff
 static inline void *nv_ioremap_wc(NvU64 phys, NvU64 size)
 {
     void *ptr = NULL;
+    return nv_ioremap_nocache(phys, size);
```

(c) **The new piece — alignment bypass** — `src/nvidia/src/kernel/gpu/bus/arch/hopper/kern_bus_gh100.c`, in `_kbusCreateStaticBar1IOMMUMapping`:

```diff
-    if (!NV_IS_ALIGNED64(peerDmaAddr, RM_PAGE_SIZE_512M))
+    if (0 && !NV_IS_ALIGNED64(peerDmaAddr, RM_PAGE_SIZE_512M))
```

That's it for source patches. Tinygrad's full patch series had hunk conflicts on 595 in `g_kern_bus_nvoc.c`, `nv_gpu_ops.c`, and `gmmu_fmt.c` (driver structure drift since 570.x), but they turned out to be unnecessary — the two regkeys below replace them.

**3. Module options** — `/etc/modprobe.d/nvidia-p2p.conf`

```
options nvidia NVreg_RegistryDwords="RMForceStaticBar1=1;ForceP2P=0x11"
```

- `RMForceStaticBar1=1` forces the static BAR1 path on (which the auto-check `kbusIsStaticBar1Supported_TU102` rejects on consumer hardware by default)
- `ForceP2P=0x11` is the runtime equivalent of tinygrad's `kernel_bif.c` patch — sets `p2pOverride = 0x11` (force read+write P2P enabled)

The kernel cmdline equivalent (`nvidia.NVreg_RegistryDwords=...`) doesn't work because the kernel cmdline parser splits on `;`. Use `/etc/modprobe.d/` and `update-initramfs -u` instead.

**4. Build + install**

```bash
make modules -j$(nproc)
# replace the DKMS-installed .ko files at /lib/modules/$(uname -r)/updates/dkms/
# then:
sudo depmod -a
sudo update-initramfs -u
```

**5. Verify**

```bash
# after reboot
cat /proc/driver/nvidia/params | grep RegistryDwords
# should show: RegistryDwords: "RMForceStaticBar1=1;ForceP2P=0x11"

nvidia-smi topo -p2p r
# should show OK, not CNS
```

Then a real CUDA test:

```c
cudaSetDevice(0); cudaDeviceEnablePeerAccess(1, 0);
// allocate on GPU1, cudaMemcpyPeer from GPU0 → success, ~28 GB/s
```

**Bandwidth**: ~28 GB/s unidirectional (PCIe 5.0 x8 — AM5 consumer ceiling). Much lower than huanzhang12's 56 GB/s on EPYC x16, but the link width is the cap, not the patch.

---

## Gotcha that wasted an hour

`nvidia.ko` loads from initramfs at early boot. After every module rebuild you must `update-initramfs -u` or the kernel keeps using the cached pre-patched copy. Symptom: `modinfo` shows the new file on disk, dmesg shows old behavior. The build date in the NVRM banner is the canonical "what's actually loaded" indicator.

---

## Downstream: vLLM and the `custom_all_reduce` hang (separate problem from P2P enablement)

This is a different limitation than the P2P enablement above. P2P enablement is solved by the recipe above. What follows is a *consequence* of how Blackwell consumer + the patched driver interact with software that uses kernel-direct peer access patterns.

**Symptom**: vLLM `tensor-parallel-size=2` with `custom_all_reduce` enabled hangs at startup right after `Registering 660 cuda graph addresses`. GPU compute util pegs at 100%, memory util at 0% — classic spin-wait deadlock pattern.

**Repro that isolates the cause** (no vLLM needed):

```cpp
__global__ void writer(volatile int *peer_ptr, int val) {
    *peer_ptr = val;
    __threadfence_system();
}
__global__ void reader(volatile int *peer_ptr, int *out, int timeout_ms) {
    long long end = clock64() + (long long)timeout_ms * 1000000;
    while (*peer_ptr == 0 && clock64() < end) {}
    *out = *peer_ptr;
}
// allocate on GPU1, write from GPU0 kernel, read on GPU1 kernel
// expected: 0xDEADBEEF. actual: 0x0
```

`cudaMemcpyPeer` works (28 GB/s), but **kernel-issued direct stores to peer addresses silently fail to propagate**. Writer kernel completes "successfully," reader spin-loops until timeout, peer memory stays at 0.

This explains the vLLM hang: vLLM's kernel uses `st.release.sys.global.u32` PTX to write a signal flag to peer memory, peer GPU spin-waits with `ld.acquire.sys.global.u32`, the write never lands → infinite spin.

**Theory of mechanism**: huanzhang12's patch redirects `GMMU_APERTURE_PEER → GMMU_APERTURE_SYS_NONCOH` in `gmmuFieldSetAperture`. CUDA copy engines apparently route around the GMMU on consumer Blackwell (or use a separate translation path that survives this aperture mismatch), so DMA still works. SM-issued stores go through the broken GMMU translation and end up writing to a sysmem address that points nowhere → silent loss.

**Things I tried to fix this that didn't help**:

1. **Forward-porting tinygrad's `gmmu_fmt.c` hunk to 595** — one-word change: `&pPte->fldAddrPeer` → `&pPte->fldAddrSysmem` in the PEER case of `gmmuFmtPtePhysAddrFld`. Compiled fine, DMA still works, but the kernel-direct repro still returns `0x0`.
2. **CUDA VMM API path** (`cuMemCreate` + `cuMemMap` + `cuMemSetAccess`). Same silent failure — both API surfaces eventually call into the same GSP-RM PTE-construction code.
3. **`VLLM_ALLREDUCE_USE_FLASHINFER=1 VLLM_FLASHINFER_ALLREDUCE_BACKEND=trtllm`**. vLLM rejects this with `FlashInfer All Reduce is disabled because it is not supported for world_size=2` (requires 4+ GPUs).
4. **vLLM's symm_mem all-reduce path**. `SymmMemCommunicator: Device capability 12.0 not supported` — Blackwell not supported yet.
5. **vLLM's `quick_all_reduce`**. ROCm only.

**Firmware-modification recon (TL;DR: don't bother)**:

I looked at whether GSP-RM (the firmware that writes the peer PTEs we care about) is patchable. On Blackwell consumer (GB202), GSP firmware lives at `/lib/firmware/nvidia/gb202/gsp/`. The relevant blobs are `bootloader-570.144.bin.zst` and `fmc-570.144.bin.zst`. After decompressing:

- `bootloader-570.144.bin`: opaque blob, entropy 7.99/8.0 (encrypted)
- `fmc-570.144.bin`: ELF 32-bit container with these sections:

```
  [2] hash         48 bytes               ← image hash
  [3] signature    96 bytes               ← ECDSA P-384 signature (48-byte r + 48-byte s)
  [4] publickey    97 bytes               ← 0x04 + 48-byte X + 48-byte Y = uncompressed P-384 point
  [5] image      ~200 KB, entropy 7.999/8.0  ← AES-encrypted firmware
```

Driver source confirms (`_kgspCreateSignatureMemdesc`, `_kgspFwContainerVerifyVersion`, `kgspGetSignatureSectionNamePrefix_GB100`). Standard secure-boot chain: GPU ROM verifies bootloader signature with fused root key → bootloader verifies FMC signature → FMC loads further modules. Image is AES-encrypted on top.

To modify GSP-RM on Blackwell consumer you'd need one of: NVIDIA's P-384 private key (no), an ECDSA P-384 break (no), a verification-code vulnerability in ROM/bootloader/FMC (Black Hat-level GPU security research), or a hardware glitch attack with custom equipment. None are afternoon-project achievable. **Kernel-direct peer access on Blackwell consumer is locked at the firmware level.**

**Practical vLLM impact**:

- `cudaMemcpyPeer` ✓
- NCCL ring all-reduce (uses copy engines) ✓
- vLLM `custom_all_reduce` ✗ (uses kernel-direct stores) — use `--disable-custom-all-reduce`
- Anything else using direct peer load/store / `__shfl_sync` across GPUs → expect breakage

**Workload + measured perf** (so others can sanity-check their setup against mine):

- Model: [`kasimat/Qwen3.6-27B-AEON-Ultimate-Uncensored-FP8-MTP`](https://huggingface.co/kasimat/Qwen3.6-27B-AEON-Ultimate-Uncensored-FP8-MTP) — hybrid linear-attention/full-attention transformer with native MTP heads, block-FP8 quant
- Container: `vllm/vllm-openai:nightly` (vLLM 0.20.2rc1.dev371, CUDA 13.0)
- Flags: `--tensor-parallel-size=2 --kv-cache-dtype=fp8 --max-model-len=65536 --max-num-seqs=2 --speculative-config '{"method":"mtp","num_speculative_tokens":3}' --reasoning-parser=qwen3 --tool-call-parser=qwen3_xml --enable-chunked-prefill --enable-prefix-caching --disable-custom-all-reduce`
- Container env: `NCCL_P2P_LEVEL=PIX NCCL_ALGO=Ring`

Single-stream decode at K=3 MTP draft, ~50% acceptance: **~100 t/s (P2P disabled baseline) → ~120 t/s (~22% gain with P2P enabled via this recipe)**, measured on 500-token completions averaged over 3 runs. The 22% comes from NCCL using the P2P fast path; `custom_all_reduce` would unlock another 10–20% if the kernel-direct path worked, but that requires firmware modification (see above).

**Comment by josephgimenez** [comment]
**Caveat — patch corrupts non-peer compute paths**

Running this on dual RTX 5090 (595.58.03 open-kernel, both regkeys set), the alignment-check bypass in `kern_bus_gh100.c` silently corrupts local-GPU compute, not just peer paths.

Repro: llama.cpp / ik_llama.cpp serving Qwen3.5/Qwen3.6 (`qwen35` hybrid SSM arch) produces NaN/Inf logits → `Failed to sample token` panic, or degenerate single-token loops (`////`). **Reproduces with `CUDA_VISIBLE_DEVICES=0` — no peer access in play.** Reverting to stock DKMS modules (same source pkg, no patch) fixes it immediately.

The patched alignment-bypass code sits in PTE installation paths shared by local GMMU mapping, so it affects kernels that only touch local HBM. The corruption is silent — no warning, no error, just bad math.

Bottom line: **API-level peer transfers work; anything that hits the patched PTE path is unsafe**, including pure single-GPU workloads. Anyone running this should treat it as P2P-API-only and not rely on numerical correctness for compute. A more surgical variant that only patches peer-PTE installation would be the right fix.
